import AuthContext from '@/contexts/auth-context'
import './globals.css'
import React from 'react'
import TanstackQueryContext from '@/contexts/tanstack-query-context'
import Navbar from '@/components/navbar/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <TanstackQueryContext>
        <AuthContext>
          <body className="text-gray-900 bg-white dark:bg-gray-800 dark:text-gray-100">
            <Navbar />
            <div className="w-full mx-auto max-w-7xl">{children}</div>
          </body>
        </AuthContext>
      </TanstackQueryContext>
    </html>
  )
}
