import AuthContext from '@/contexts/auth-context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthContext>
        <body className="bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100">
          {children}
        </body>
      </AuthContext>
    </html>
  )
}
